'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class bookconfirm

    '''<summary>
    '''PreBookInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PreBookInfo As Global.System.Web.UI.WebControls.FormView

    '''<summary>
    '''promocodeval control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents promocodeval As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''Promocode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Promocode As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''Promomsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Promomsg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Confbook control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Confbook As Global.System.Web.UI.HtmlControls.HtmlButton
End Class
