'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class carvendorprofile

    '''<summary>
    '''FormView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FormView1 As Global.System.Web.UI.WebControls.FormView

    '''<summary>
    '''DataList1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DataList1 As Global.System.Web.UI.WebControls.DataList

    '''<summary>
    '''DataList3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DataList3 As Global.System.Web.UI.WebControls.DataList

    '''<summary>
    '''DataList4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DataList4 As Global.System.Web.UI.WebControls.DataList

    '''<summary>
    '''DataList5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DataList5 As Global.System.Web.UI.WebControls.DataList

    '''<summary>
    '''DataList6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DataList6 As Global.System.Web.UI.WebControls.DataList

    '''<summary>
    '''odpwd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odpwd As Global.System.Web.UI.HtmlControls.HtmlInputPassword

    '''<summary>
    '''nwpwd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents nwpwd As Global.System.Web.UI.HtmlControls.HtmlInputPassword

    '''<summary>
    '''cnwpwd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cnwpwd As Global.System.Web.UI.HtmlControls.HtmlInputPassword

    '''<summary>
    '''chgpwd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chgpwd As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''DataList2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DataList2 As Global.System.Web.UI.WebControls.DataList

    '''<summary>
    '''Reg_no control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Reg_no As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''segmentt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents segmentt As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''fueltype control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fueltype As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''transtype control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents transtype As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''seatcap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents seatcap As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl

    '''<summary>
    '''minprice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents minprice As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl

    '''<summary>
    '''minkm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents minkm As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl

    '''<summary>
    '''Cty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cty As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''pickuplocality control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pickuplocality As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''pickuploc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pickuploc As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''vphoto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vphoto As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '''<summary>
    '''vrc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vrc As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '''<summary>
    '''vins control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vins As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '''<summary>
    '''vpucc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vpucc As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '''<summary>
    '''AddCar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddCar As Global.System.Web.UI.HtmlControls.HtmlButton
End Class
