'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class registercust

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''emailadd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents emailadd As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl

    '''<summary>
    '''ent_pwd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ent_pwd As Global.System.Web.UI.HtmlControls.HtmlInputPassword

    '''<summary>
    '''conf_pwd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents conf_pwd As Global.System.Web.UI.HtmlControls.HtmlInputPassword

    '''<summary>
    '''cname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cname As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''mobileno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mobileno As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''idtype_ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents idtype_ As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''idcardno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents idcardno As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''idcard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents idcard As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '''<summary>
    '''dl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dl As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '''<summary>
    '''photo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents photo As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '''<summary>
    '''SubmitCust control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubmitCust As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''signupstatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents signupstatus As Global.System.Web.UI.WebControls.Label
End Class
